# from random import randrange, randint
# print(randrange(5, 100, 5))
# print(randint(0,20)*5)
item = input("Enter the item name:")
sales = input("Enter the quantity:")
# print("{0}","{1}".format(item, sales))
# print(item + '""' + sales)
print('"' + item + '",' + sales)
print("{0},{1}".format(item,sales))
print('"%s",%s' %(item,sales))